version: '3.7'

services:
  inventory:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql:3306/kometsales?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.properties.hibernate.naming.physical-strategy": "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
    restart: always
    depends_on:
      - mysql
    networks:
      - host

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: kometsales
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/db.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    networks:
      - host

networks:
  host:
